package:
  name: xdesign
  version: 'alpha'

source:
  path: .

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python={{ python }}
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
  run:
    - cached-property
    - matplotlib
    - numpy
    - python={{ python }}
    - scipy

test:
  requires:
    - nose
  imports:
    - xdesign
    - xdesign.geometry
    - xdesign.metrics
    - xdesign.phantom
  source_files:
    - tests/*
  commands:
    - nosetests

about:
  home: http://xdesign.readthedocs.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Benchmarking and optimization tools for tomography.'
  description: |
    XDesign is an open-source Python package for creating x-ray imaging
    phantoms, simulating data acquisition, and benchmarking x-ray
    tomographic image reconstruction.
  doc_url: https://xdesign.readthedocs.io
  dev_url: https://github.com/tomography/xdesign

extra:
  recipe-maintainers:
    - carterbox
