package:
  name: xdesign
  version: '0.1.0'

source:
  git_url: https://github.com/decarlof/xdesign.git

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy    
    - scipy
    - six
    - matplotlib
    - phasepack
    - cached-property

test:
  # Python imports
  imports:
    - xdesign

about:
  home: http://xdesign.readthedocs.io
  license: BSD-3
  summary: 'Benchmarking and optimization tools for tomography.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
